import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const quicksand = Quicksand({ 
  subsets: ['latin'],
  variable: '--font-quicksand'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={quicksand.variable}>
      <head>
        <style>{`
          body {
            font-family: Helvetica, Arial, sans-serif;
          }
        `}</style>
      </head>
      <body
        className={`${inter.variable} antialiased font-quicksand`}
      >
        {children}
      </body>
    </html>
  );
}
